# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

variables:
  HOST_LDC_VERSION: 1.14.0

trigger:
  - master

jobs:
- job: Linux
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    CI_OS: linux
  steps:
    - template: .azure-pipelines/posix.yml
  strategy:
    matrix:
      ldc-ubuntu-min-test:
        TEST_GROUP: ldc-ubuntu-min-test
      dmd-ubuntu-min-test:
        TEST_GROUP: dmd-ubuntu-min-test
      dmd-ubuntu-latest-test:
        TEST_GROUP: dmd-ubuntu-latest-test
      dmd-ubuntu-latest-dub:
        TEST_GROUP: dmd-ubuntu-latest-dub
      dmd-centos7-min-release:
        TEST_GROUP: dmd-centos7-min-release
