# Each step starts in the checked-out source directory,
# environment variables aren't persisted across steps.

steps:
- checkout: self
  submodules: false
  fetchDepth: 1
- script: |
    set -ex
    cd ..
    export DEBIAN_FRONTEND=noninteractive
    sudo dpkg --add-architecture i386
    sudo apt install xz-utils
  displayName: Setup
- script: |
    cd ..
    # Download & extract host LDC
    curl -L -o ldc2.tar.xz https://github.com/ldc-developers/ldc/releases/download/v$HOST_LDC_VERSION/ldc2-$HOST_LDC_VERSION-$CI_OS-x86_64.tar.xz
    mkdir host-ldc
    tar -xf ldc2.tar.xz --strip 1 -C host-ldc
    export DC_PATH="$PWD/host-ldc/bin"
    $DC_PATH/ldc2 --version

    echo "##vso[task.setvariable variable=DC_PATH]$DC_PATH"
  displayName: Install ldc
- script: |
    set -ex
    export PATH="$DC_PATH:$PATH"
    ./Docker/docker.d --group $TEST_GROUP
  displayName: Run docker
